name: Build STM32

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Toolchain
        run: sudo apt update && sudo apt install -y gcc-arm-none-eabi

      - name: Build Firmware
        run: |
          mkdir build
          arm-none-eabi-gcc -mcpu=cortex-m3 -mthumb -O2 -nostdlib -ffreestanding -T linker.ld \
          Core/Src/main.c \
          Core/Src/system_stm32f1xx.c \
          Core/Startup/startup_stm32f103c8.s \
          -o build/firmware.elf

          arm-none-eabi-objcopy -O binary build/firmware.elf build/firmware.bin

          arm-none-eabi-size build/firmware.elf

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/firmware.bin
