name: STM32 Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Toolchain
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi

    - name: Build Project
      run: |
        cat > linker.ld << 'EOF'
        MEMORY
        {
          FLASH (rx)  : ORIGIN = 0x08000000, LENGTH = 64K
          RAM (rwx)   : ORIGIN = 0x20000000, LENGTH = 20K
        }

        _estack = 0x20005000;

        SECTIONS
        {
          .text :
          {
            *(.isr_vector)
            *(.text*)
            *(.rodata*)
          } > FLASH

          .data : { *(.data*) } > RAM
          .bss  : { *(.bss*) *(COMMON) } > RAM
        }
        EOF

        arm-none-eabi-gcc \
        Core/Src/main.c  \
        Core/Src/system_stm32f1xx.c \
        Core/Startup/*.s \
        -T linker.ld \
        -mcpu=cortex-m3 \
        -mthumb \
        -nostdlib \
        -Wl,--gc-sections \
        -o firmware.elf

        arm-none-eabi-objcopy -O ihex firmware.elf firmware.hex

    - name: Upload HEX
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: firmware.hex
